name: WakaTime Readme

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: jameskiongo/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: "░▒▓█"
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
          SHOW_TITLE: true
